<!DOCTYPE html>
<html lang="sv-SE">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <title>MAD - Magnus Lidmyr, Andreas Åkerlöf, Daniel Hessling</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <div class="container">

    <header>
    </header>

    <!-- Header templates -->
    <template id="logoTemplate">
      <div id="logo">
        <img src="logo.png" id="logo" alt="logo">
      </div>
    </template>

    <template id="navTemplate">
      <nav>
        <a href="" id="navAllEntries">Alla inlägg</a>
        <a href="" id="navPrivateEntries">Mina inlägg</a>
        <a href="" id="navNewEntry">Skriv nytt inlägg</a>
      </nav>
    </template>

    <template id="memberLogoutTemplate">
      <div id="memberLogout">
        <span id="loggedInMember">Olle ollesson |</span>
        <span id="logoff"><a href="">Logga ut</a></span>
      </div>
    </template>
    
    <!-- Header templates - END -->

    <hr>

    <main>
    </main>

    <!-- Main templates -->

    <template id="loginFormTemplate">
      <form class="loginDiv" id="loginForm">
        <table id="loginTable">
          <tr>
            <td colspan="4">
              <h1>Logga in</h1>
            </td>
          </tr>
          <tr>
            <td colspan="3"><label for="username">Användarnamn:</label></td>
            <td><input type="text" name="username"></td>
          </tr>
          <tr>
            <td colspan="3"><label for="password">Lösenord:</label></td>
            <td><input type="password" name="password"></td>
          </tr>
          <tr>
            <td></td>
            <td colspan="4"><button type="submit" class="btn">Logga in</button></td>
          </tr>
          <tr>
            <td colspan="2" id="loginFormError">
            </td>
          </tr>
        </table>
      </form>
    </template>

    <template id="registerFormTemplate">
      <form class="registerDiv" id="registerForm">
        <table id="registerTable">
          <tr>
            <td colspan="4">
              <h1>Bli medlem</h1>
            </td>
          </tr>
          <tr>
            <td colspan="3"><label for="username">Användarnamn:</label></td>
            <td><input type="text" name="username"></td>
          </tr>
          <tr>
            <td colspan="3"><label for="password">Lösenord:</label></td>
            <td><input type="password" name="password"></td>
          </tr>
          <tr>
            <td></td>
            <td colspan="4"><button type="submit" class="btn">Bli medlem</button></td>
          </tr>
        </table>
      </form>
    </template>
  
    <template id="memberSuccessTemplate">
      <div id="memberSuccess">
        <h1>Grattis!</h1>
        <p>Du är nu medlem</p>
      </div>
    </template>
    
    <template id="searchTemplate">
      <!-- DANIEL FIXA KOD HÄR -->
    </template>

    <template id="entriesTemplate">
      <div id="entriesListing">
      </div>
    </template>
 
    <template id="entryTemplate">
      <div id="newEntry">
        <form id="newEntryForm">
          <table id="newEntryTable">
            <tr>
              <td colspan="4">
                <h1>Nytt inlägg</h1>
              </td>
            </tr>
            <tr>
              <td colspan="3"><label for="entryTitle">Titel:</label></td>
            </tr>
            <tr>
              <td><input type="text" name="entryTitle"></td>
            </tr>
            <tr>
              <td colspan="3"><label for="post">Inlägg:</label></td>
            </tr>
            <tr>
              <td><textarea name="newEntry"></textarea></td>
            </tr>
            <tr>
              <td colspan="4"><button type="submit" class="btn">Lägg till inlägg</button></td>
            </tr>
          </table>
        </form>
      </div>
    </template>
  
    <template id="newEntryTemplate">
      <div id="newEntry">
        <form id="newEntryForm">
          <table id="newEntryTable">
            <tr>
              <td colspan="4">
                <h1>Nytt inlägg</h1>
              </td>
            </tr>
            <tr>
              <td colspan="3"><label for="newEntryTitle">Titel:</label></td>
            </tr>
            <tr>
              <td><input type="text" name="newEntrytitle"></td>
            </tr>
            <tr>
              <td colspan="3"><label for="newEntryPost">Inlägg:</label></td>
            </tr>
            <tr>
              <td><textarea name="newEntryPost"></textarea></td>
            </tr>
            <tr>
              <td colspan="4"><button type="submit" class="btn">Uppdatera inlägg</button></td>
            </tr>
          </table>
        </form>
      </div>
    </template>
    
    <template id="editEntryTemplate">
      <div id="editEntry">
        <form id="editEntryForm">
          <table id="editEntryTable">
            <tr>
              <td colspan="4">
                <h1>Redigera inlägg</h1>
              </td>
            </tr>
            <tr>
              <td colspan="3"><label for="editEntryTitle">Titel:</label></td>
            </tr>
            <tr>
              <td><input type="text" name="editEntrytitle"></td>
            </tr>
            <tr>
              <td colspan="3"><label for="editEntryPost">Inlägg:</label></td>
            </tr>
            <tr>
              <td><textarea name="editEntryPost"></textarea></td>
            </tr>
            <tr>
              <td colspan="4"><button type="submit" class="btn">Uppdatera inlägg</button></td>
            </tr>
          </table>
        </form>
      </div>
    </template>

    <template id="membersTemplate">
      <table id="allUsers">
        <tr>
          <td colspan="4">
            <h1>Alla användare</h1>
          </td>
        </tr>
        <tr>
          <td>Användarnamn:</td>
          <td>Namn:</td>
          <td></td>
        </tr>
      </table>
      <table id="user">
        <tr>
          <td>dude_yeah33</td>
          <td>Niklas Pellesson</td>
          <td><button name="showUser">Visa användare</td>
        </tr>
      </table>
    </template>

    <!-- Main templates - END -->

    <hr>

    <footer>
      <span id="footer-copyright">Copyright &copy; MAD - Magnus Lidmyr, Andreas Åkerlöf, Daniel Hessling</span>
    </footer>
  </div>
  <script src="main.js"></script>
</body>
</html>