<!DOCTYPE html>
<html lang="sv-SE">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <title>MAD - Magnus Lidmyr, Andreas Åkerlöf, Daniel Hessling</title>
    <link rel="stylesheet" href="style.css">
</head>

<body>

    <div class="container">
        <header>
            <div id="logo">
                <img src="logo.png" id="logo" alt="logo">
            </div>
            <template id="navTemplate">
                <nav>
                    <a href="#">Alla inlägg</a>
                    <a href="#">Mina inlägg</a>
                    <a href="#">Skriv nytt inlägg</a>
                </nav>
            </template>
            <template id="memberLogoutTemplate">
                <div id="memberLogout">
                    <span id="loggedInMember">Olle ollesson |</span>
                    <span id="logout"><a href="#">Logga ut</a></span>
                </div>
            </template>
        </header>
        <hr>
        <main>
            <div id="logreg">
                <template id="loginFormTemplate">
                    <div class="loginDiv">
                        <table id="loginTable">
                            <tr>
                                <td colspan="4">
                                    <h1>Logga in</h1>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="3"><label for="username">Användarnamn:</label></td>
                                <td><input type="text" name="username"></td>
                            </tr>
                            <tr>
                                <td colspan="3"><label for="password">Lösenord:</label></td>
                                <td><input type="password" name="password"></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td colspan="4"><button type="submit" class="btn">Logga in</button></td>
                            </tr>
                        </table>
                    </div>
                </template>
                <template id="registerFormTemplate">
                    <div class="registerDiv">
                        <table id="registerTable">
                            <tr>
                                <td colspan="4">
                                    <h1>Bli medlem</h1>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="3"><label for="username">Användarnamn:</label></td>
                                <td><input type="text" name="username"></td>
                            </tr>
                            <tr>
                                <td colspan="3"><label for="password">Lösenord:</label></td>
                                <td><input type="password" name="password"></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td colspan="4"><button type="submit" class="btn">Bli medlem</button></td>
                            </tr>
                        </table>
                    </div>
                    <template id="memberSuccessTemplate">
                        <div id="memberSuccess">
                            <h1>Grattis!</h1>
                            <p>Du är nu medlem</p>
                        </div>
                    </template>
                </template>
            </div>
            <template id="entriesTemplate">
                <h1>20 senaste inläggen</h1>

                <div class="post">
                    <h3>Inlägg #1</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti expedita animi ipsam vel
                        explicabo veniam nulla maiores ab nam ad.</p>
                </div>
                <div class="post">
                    <h3>Inlägg #2</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti expedita animi ipsam vel
                        explicabo veniam nulla maiores ab nam ad.</p>
                </div>
                <div class="post">
                    <h3>Inlägg #3</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti expedita animi ipsam vel
                        explicabo veniam nulla maiores ab nam ad.</p>
                </div>
                <div class="post">
                    <h3>Inlägg #4</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti expedita animi ipsam vel
                        explicabo veniam nulla maiores ab nam ad.</p>
                </div>
            </template>

            <template id="entryTemplate">
                <div id="newEntry">
                    <form id="newEntryForm">
                        <table id="newEntryTable">
                            <tr>
                                <td colspan="4">
                                    <h1>Nytt inlägg</h1>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="3"><label for="entryTitle">Titel:</label></td>
                            </tr>
                            <tr>
                                <td><input type="text" name="entryTitle"></td>
                            </tr>
                            <tr>
                                <td colspan="3"><label for="post">Inlägg:</label></td>
                            </tr>
                            <tr>
                                <td><textarea name="newEntry"></textarea></td>
                            </tr>
                            <tr>
                                <td colspan="4"><button type="submit" class="btn">Lägg till inlägg</button></td>
                            </tr>
                        </table>
                    </form>
                </div>
            </template>

            <template id="editEntryTemplate">
                <div id="editEntry">
                    <form id="editEntryForm">
                        <table id="editEntryTable">
                            <tr>
                                <td colspan="4">
                                    <h1>Redigera inlägg</h1>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="3"><label for="editEntryTitle">Titel:</label></td>
                            </tr>
                            <tr>
                                <td><input type="text" name="editEntrytitle"></td>
                            </tr>
                            <tr>
                                <td colspan="3"><label for="editEntryPost">Inlägg:</label></td>
                            </tr>
                            <tr>
                                <td><textarea name="editEntryPost"></textarea></td>
                            </tr>
                            <tr>
                                <td colspan="4"><button type="submit" class="btn">Uppdatera inlägg</button></td>
                            </tr>
                        </table>
                    </form>
                </div>
            </template>
            <template id="membersTemplate">
                <table id="allUsers">
                    <tr>
                        <td colspan="4">
                            <h1>Alla användare</h1>
                        </td>
                    </tr>
                    <tr>
                        <td>Användarnamn:</td>
                        <td>Namn:</td>
                        <td></td>
                    </tr>
                </table>
                <table id="user">
                    <tr>
                        <td>dude_yeah33</td>
                        <td>Niklas Pellesson</td>
                        <td><button name="showUser">Visa användare</td>
                    </tr>
                </table>
            </template>
        </main>
        <hr>
        <footer>
            <span id="footer-copyright">Copyright &copy; MAD - Magnus Lidmyr, Andreas Åkerlöf, Daniel Hessling</span>
        </footer>
    </div>

</body>

</html>